{% set name = "tabascal" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/chrisfinlay/tabascal.git

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.10,<3.13
    - pip
    - setuptools >=64

  run:
    - python >=3.10,<3.13
    - jax  # 👉 CPU-Version
    - xarray
    - zarr <3.0.0
    - dask <=2024.10.0
    - dask-ms >=0.2.21
    - scipy
    - tqdm
    - pandas
    - matplotlib
    - astropy
    - requests
    - numpy <2.0.0
    - pyyaml
    - skyfield

#test:
#  imports:
#    - tabascal
#  commands:
#    - sim-vis --help

about:
  home: https://github.com/chrisfinlay/tabascal
  summary: "Trajectory based RFI subtraction and calibration using Bayesian methods for radio interferometric data."
  license: LicenseRef-CUSTOM
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Andreas Wassmer (andreas.wassmer@fhnw.ch)
